### ISSUE TITLE
please give us mockup service

### ISSUE THREAD

**Issue by VanHop94** [patelmayankce/angular-8-boilerplate#4]
Thank you for your project. It's very helpful for me. But now, I can not try using because login does not work. Thank you

**Comment by patelmayankce** [comment]
Thanks for checking out.
The login screen is connected to API through Authentication service.
https://github.com/patelmayankce/angular-8-boilerplate/blob/master/src/app/core/authentication/authentication.service.ts
so you need to connect your API endpoint in environment files. https://github.com/patelmayankce/angular-8-boilerplate/tree/master/src/environments

**Comment by VanHop94** [comment]
Yes, I know, I mean could you give me your service mockup to test this project, instead of creating new service by myself. It'll take more time

**Comment by patelmayankce** [comment]
You can follow https://github.com/patelmayankce/hapi-18-boilerplate node HAPI FW boilerplate to setup API. ( it uses MongoDB as database)
